version: "3.3"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Rushi*123
      MYSQL_DATABASE: pyton-project-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  app:
    build:
      context: ./app
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://root:Rushi*123@db:3306/pyton-project-db
    ports:
      - "8000:8000"
    restart: always

volumes:
  mysql_data:
