# k8s/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_USER: UnVzaGkqMTIz                    # Base64 Encoded "root"
  MYSQL_ROOT_PASSWORD: UnVzaGkqMTIz        # Base64 Encoded "Rushi*123"
